---
- name: make ta home
  hg:
    repo=https://bitbucket.org/a_baez/ta-userhome
    dest="{{ ta_home }}"

- name: make module directory
  file:
    dest="{{ ta_home }}/modules"
    state=directory

- name: get ta common module
  hg:
    repo=https://bitbucket.org/a_baez/ta-common
    dest="{{ ta_home }}/modules/common"

- name: clone rust module
  hg:
    repo=https://bitbucket.org/a_baez/ta-rust
    dest="{{ ta_home }}/modules/rust"

- name: clone hastebin module
  hg:
    repo=https://bitbucket.org/a_baez/ta-hastebin
    dest="{{ ta_home }}/modules/hastebin"

- name: clone toml module
  hg:
    repo=https://bitbucket.org/a_baez/ta-toml
    dest="{{ ta_home }}/modules/toml"

- name: clone markdown module
  git:
    repo=https://github.com/rgieseke/ta-markdown.git
    dest="{{ ta_home }}/modules/markdown"
