---
- name: Install dependencies
  yum: name={{ item }} state=latest
  with_items:
    - python
    - python-pip

- name: Install docker
  yum: name="docker-io" state=latest

- name: install docker-compose
  pip: name=docker-compose
