---
- name: install EPEL repository
  yum:
    name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state=present

- name: update all packages
  yum: name=* state=latest

- name: install other dependencies
  yum: name={{ item }} state=latest
  with_items:
    - curl
    - wget
    - vim

- name: install DVCS
  yum: name={{ item }} state=latest
  with_items:
    - git
    - mercurial
