---
- name: clone luarocks
  git:
    repo=https://github.com/keplerproject/luarocks.git
    dest="{{ tmp_dir }}/luarocks"
    version=v2.2.1

- name: install luarocks
  shell: ./configure --lua-version=5.2 --prefix=/usr/local --with-lua=/usr ; make build; make install
  args:
    chdir: "{{ tmp_dir }}/luarocks"
