---
- name: clone luarocks
  git:
    repo=https://github.com/keplerproject/luarocks.git
    dest="{{ tmp_dir }}/luarocks"
    version=v2.2.1

- name: configure luarocks
  command: ./configure --lua-version=5.2 --prefix=/usr/local --with-lua=/usr
  args:
    chdir: "{{ tmp_dir }}/luarocks"

- name: build luarocks
  command: make build
  args:
    chdir: "{{ tmp_dir }}/luarocks"

- name: install luarocks
  command: make install
  args:
    chdir: "{{ tmp_dir }}/luarocks"
