---
- name: install the requirements for RedHat based
  yum: name={{ item }} state=latest
  with_items:
    - pkg-config
    - fuse
    - union-fs
  when: ansible_os_family == "RedHat"

- name: install the requirements for Debian based
  apt: name={{ item }} state=latest
  with_items:
    - pkg-config
    - fuse
    - union-fs
  when: ansible_os_family == "Debian"
