---
- name: install zsh and dependencies
  include: "dependencies.yml"

- name: use some modueeles for zsh
  include: "modules.yml"

- name: use user configuration for zsh
  include: "configuration.yml"

- name: change shell from bash to zsh for vagrant
  shell: chsh -s $(which zsh)
