---
- name: prerequisites for build
  yum: name={{ item }} state=latest
  with_items:
    - git
    - make
    - gcc


- name: Install epel
  rpm:
    name="dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-{{ epel }}.rpm"
    state=present
