---
- name: installation and configuration of redis

- name: dependencies
  include: "dependencies.yml"

- name: installation
  yum: name=redis state=latest

- name: configuration
  include: "configuration.yml"
